# Generated by Django 4.0.5 on 2022-06-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_jsonupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='json_files'),
        ),
    ]
