# Generated by Django 4.0.5 on 2022-06-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_jsonupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonupload',
            name='filename',
            field=models.CharField(default='demo.json', max_length=20),
        ),
    ]
